#!/bin/bash

HADOOP_BASE_PORT=23000
MASTER="localhost"
SLAVES="localhost"

#####################################################################################################

NAMENODE=$MASTER
NAMENODE_PORT=$(($HADOOP_BASE_PORT + 10))
NAMENODE_BKUP_PORT=$(($HADOOP_BASE_PORT + 100))
NAMENODE_BKUP_HTTP_PORT=$(($HADOOP_BASE_PORT + 105))
NAMENODE_HTTP_PORT=$(($HADOOP_BASE_PORT + 70))
NAMENODE_HTTPS_PORT=$(($HADOOP_BASE_PORT + 470))
SECONDARY_NAMNODE_HTTP_PORT=$(($HADOOP_BASE_PORT + 90))
DATANODE_PORT=$(($HADOOP_BASE_PORT + 20))
DATANODE_HTTP_PORT=$(($HADOOP_BASE_PORT + 75))
DATANODE_HTTPS_PORT=$(($HADOOP_BASE_PORT + 475))
DATANODE_IPC_PORT=$(($HADOOP_BASE_PORT + 23))

JOBHISTORY_PORT=$(($HADOOP_BASE_PORT + 25))
JOBHISTORY_WEBAPP_PORT=$(($HADOOP_BASE_PORT + 230))

MR_SHUFFLE_PORT=$(($HADOOP_BASE_PORT + 80))

RESOURCEMANAGER=$MASTER
JOBHISTORY=$RESOURCEMANAGER
RM_PORT=$(($HADOOP_BASE_PORT + 140))
RM_SCHEDULER_PORT=$(($HADOOP_BASE_PORT + 130))
RM_WEBAPP_PORT=$(($HADOOP_BASE_PORT + 30))
RM_RESOURCETRACKER_PORT=$(($HADOOP_BASE_PORT + 125))
RM_ADMIN_PORT=$(($HADOOP_BASE_PORT + 141))

NM_LOCALIZER_PORT=$(($HADOOP_BASE_PORT + 344))
NM_WEBAPP_PORT=$(($HADOOP_BASE_PORT + 999))

XML_CONFIGS='core-site.xml hdfs-site.xml mapred-site.xml yarn-site.xml'

for FILE in $XML_CONFIGS; do
  sed -i -e "s|@NAMENODE@|$NAMENODE|" $FILE
  sed -i -e "s|@NAMENODE_PORT@|$NAMENODE_PORT|" $FILE
  sed -i -e "s|@NAMENODE_BKUP_PORT@|$NAMENODE_BKUP_PORT|" $FILE
  sed -i -e "s|@NAMENODE_BKUP_HTTP_PORT@|$NAMENODE_BKUP_HTTP_PORT|" $FILE
  sed -i -e "s|@NAMENODE_HTTP_PORT@|$NAMENODE_HTTP_PORT|" $FILE
  sed -i -e "s|@NAMENODE_HTTPS_PORT@|$NAMENODE_HTTPS_PORT|" $FILE
  sed -i -e "s|@SECONDARY_NAMNODE_HTTP_PORT@|$SECONDARY_NAMNODE_HTTP_PORT|" $FILE
  sed -i -e "s|@DATANODE_PORT@|$DATANODE_PORT|" $FILE
  sed -i -e "s|@DATANODE_HTTP_PORT@|$DATANODE_HTTP_PORT|" $FILE
  sed -i -e "s|@DATANODE_HTTPS_PORT@|$DATANODE_HTTPS_PORT|" $FILE
  sed -i -e "s|@DATANODE_IPC_PORT@|$DATANODE_IPC_PORT|" $FILE
  sed -i -e "s|@JOBHISTORY@|$JOBHISTORY|" $FILE
  sed -i -e "s|@JOBHISTORY_PORT@|$JOBHISTORY_PORT|" $FILE
  sed -i -e "s|@JOBHISTORY_WEBAPP_PORT@|$JOBHISTORY_WEBAPP_PORT|" $FILE
  sed -i -e "s|@MR_SHUFFLE_PORT@|$MR_SHUFFLE_PORT|" $FILE
  sed -i -e "s|@RESOURCEMANAGER@|$RESOURCEMANAGER|" $FILE
  sed -i -e "s|@RM_PORT@|$RM_PORT|" $FILE
  sed -i -e "s|@RM_SCHEDULER_PORT@|$RM_SCHEDULER_PORT|" $FILE
  sed -i -e "s|@RM_WEBAPP_PORT@|$RM_WEBAPP_PORT|" $FILE
  sed -i -e "s|@RM_RESOURCETRACKER_PORT@|$RM_RESOURCETRACKER_PORT|" $FILE
  sed -i -e "s|@RM_ADMIN_PORT@|$RM_ADMIN_PORT|" $FILE
  sed -i -e "s|@NM_LOCALIZER_PORT@|$NM_LOCALIZER_PORT|" $FILE
  sed -i -e "s|@NM_WEBAPP_PORT@|$NM_WEBAPP_PORT|" $FILE
done

echo $MASTER > ./masters

rm -f slaves
for SLAVE in $MASTER $SLAVES; do
  echo $SLAVE >> ./slaves
done
